-- =============================================================================
-- Migration: 0031_fix_dev_sponsor.sql
-- Purpose:   (Intentionally a no-op in production.)
--
-- This migration previously seeded a local-development "Test Sponsor Corp" and a
-- 'devsponsor@test.local' account. That is dev-only test data and must never be
-- created in production. It also relied on an ON CONFLICT (company_name) target
-- for which no unique constraint exists, so it is not safely replayable.
--
-- The dev sponsor is provisioned by the local seed/test tooling instead, so this
-- migration is now empty. The numbered file is kept so migration history stays
-- consistent across environments that already applied it.
-- =============================================================================
