-- 0049_drop_unused_team_members.sql
-- M-4 / COPPA hardening.
--
-- The teams.team_members JSONB column (added in 0025 for an "About the Team" portfolio
-- section) was never wired up: no server action writes it and no UI reads it (verified —
-- zero references anywhere outside the generated types file, and it is absent from the
-- teamOnboardingSchema). Every row holds the default '[]'.
--
-- On an FTC platform "team members" are students, so an unused column literally designed
-- to hold a student roster is a standing COPPA liability and directly conflicts with the
-- "zero student PII columns" core mandate. Drop it. (coach_photo_url, the *adult* coach's
-- photo which IS used by the portfolio, is intentionally retained.)
--
-- NOTE: regenerate lib/supabase/types.ts from the DB after applying
-- (`supabase gen types typescript`) so the generated Database type no longer lists this column.
ALTER TABLE teams DROP COLUMN IF EXISTS team_members;
